import { catchAsyncError } from "../../middleWares/catchAsyncError.js";

export const getUser = catchAsyncError(async(req,res,next) => {
    
})

export const updateUser = catchAsyncError(async(req,res,next) => {

})

export const deleteUser = catchAsyncError(async(req,res,next) => {

})